set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_SYSTEM_VERSION 10.15)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(TOOLCHAIN_PATH /usr/local/bin)
set(CMAKE_CXX_STANDARD 17)

set(CMAKE_C_COMPILER     "${TOOLCHAIN_PATH}/gcc")
set(CMAKE_CXX_COMPILER   "${TOOLCHAIN_PATH}/g++")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_CROSS_COMPILING TRUE)